Repository cloudeteer/terraform-azurerm-vm, pull requests merged in 2024-09, with the labels that each got.

#12 Update configurations to latest standard
  .github/ISSUE_TEMPLATE/bug-template.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-template.yml
  .github/workflows/module-ci.yaml
  CHANGELOG.md
Labels: ignore-release

#20 Remote testing greatly improved
  tests/remote/main.tf
  tests/remote/main.tftest.hcl
  tests/remote/providers.tf
  tests/remote/resources.tf
  tests/remote/terraform.tf
Labels: ignore-release

#14 Add ed25519 SSH Key support
  README.md
  r-authentication.tf
  tests/local/input_authentication.tftest.hcl
  tests/remote/main.tf
  tests/remote/terraform.tf
  variables.tf
  versions.tf
Labels: feature

#29 Add hotpatching feature
  README.md
  r-vm.tf
  tests/local/input_enable_hotpatching.tftest.hcl
  variables.tf
Labels: feature

#33 Make sure that `hotpatching_enabled` and `bypass_platform_safety_checks_on_user_schedule_enabled` are not set at the same time.
  variables.tf
Labels: fix

#32 Add `var.tags` to OS-disk
  README.md
  r-vm.tf
  tests/examples/mocks/azurerm_managed_disk.tfmock.hcl
  tests/local/mocks/azurerm_managed_disk.tfmock.hcl
  variables.tf
Labels: feature

#30 Block AzAPI provider `>= 2.0.0`
  README.md
  versions.tf
Labels: fix

#26 Use min version 3.1.0 on "random" provider
  README.md
  tests/remote/terraform.tf
  versions.tf
Labels: fix
