Repository cloudeteer/terraform-azurerm-vm, pull requests merged in 2025-04, with the labels that each got.

#69 Support data disk `create_option = Copy`
  README.md
  r-disk.tf
  variables.tf
Labels: feature

#67 Tidy up logic of local.identity_type
  tests/local/input_entra_id.tftest.hcl
  variables.tf
Labels: fix

#70 Update config files
  .gitignore
  .pre-commit-config.yaml
  .terraform-docs.yaml
  .tflint.examples.hcl
  .tflint.hcl
  .tflint.tests.hcl
Labels: ignore-release

#72 Implement AD Domain Join functionality
  README.md
  r-extensions.tf
  variables.tf
Labels: feature

#73 Add domain join example
  examples/domain_join/README.md
  examples/domain_join/main.tf
  examples/domain_join/tests_override.tf
  tests/examples/domain_join.tftest.hcl
Labels: ignore-release
